### ISSUE TITLE
Automatic server and server type finder

### ISSUE THREAD

**Issue by janniksam** [janniksam/Akinator.Api.Net#11]

**Comment by ahmed605** [comment]
Once the initial code is ready, I will open the new branch 👍

**Comment by janniksam** [comment]
Cool, happy to review. 👍

**Comment by janniksam** [comment]
Any news?
If you're busy, I could help you.

**Comment by ahmed605** [comment]
@janniksam yeah, I'm very busy because of school work (studying), I will finish my exams next month so I will be able to work on this feature then, I'm very sorry for that

**Comment by janniksam** [comment]
Do you mind showing me the "trick" (/api), so I can start implementing it? I have some time these days :)

**Comment by ahmed605** [comment]
@janniksam not at all, here's the API endpoint: `https://global3.akinator.com/ws/instances_v2.php?media_id=13&footprint=82de69085436aba8a6f6b37c0d5c8a1e&lang=LANG_ISO&subject_id=SERVER_TYPE&mode=https`

Replace `LANG_ISO` with the language ISO code (e.g. ar, en, es, ...)

Replace `SERVER_TYPE` with the server  type id: 
- 2 = Object
- 14 = Animal
- 1 = Person

**Comment by ahmed605** [comment]
@janniksam have you got my message ^?

**Comment by janniksam** [comment]
Thank you I'll check it out in the next couple days 👍

**Comment by ahmed605** [comment]
@janniksam I have found the `SERVER_TYPE` (ID)/`subject_id` of server type: "movies", it's `13`

**Comment by ahmed605** [comment]
Also you can use `subject_id=0` to get a full list of all supported server types and URLs of any language

**Comment by janniksam** [comment]
Hey Ahmed, unfortunately I did not find the time yet, to do anything ;)

**Comment by ahmed605** [comment]
I have found an endpoint that returns a list of all languages, servers, supported server types and URLs `https://global3.akinator.com/ws/instances_v2.php?media_id=14&footprint=cd8e6509f3420878e18d75b9831b317f&mode=https`

**Comment by janniksam** [comment]
So, my idea is to write a new AkinatorConfigurationBuilder class, which take the language-enum and the server type and will gives back either NULL (when nothing was found) or a AkinatorConnectionConfiguration object. The existing AkinatorClient will take the configuration as  a new constructor parameter instead of all the old ones.
