### ISSUE TITLE
Randomize server in case there are multiple

### ISSUE THREAD

**Issue by janniksam** [janniksam/Akinator.Api.Net#12]
Possibility to randomize the server type. Instead of selecting a specific type (animal, person, object)

**Comment by ahmed605** [comment]
What I actually meant is to select a server randomly from available servers in the range of the same language and type because the endpoint that I have found returns 4 servers for the same language and server type

**Comment by janniksam** [comment]
Ahh, I see. 👍 
I don't think, "randomizing" is the way to go here. In my opinion it should be some sort of "brute force". like if the first server is down fallback to the second one and so on.
